apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-deployment
  labels:
    app: crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm
  template:
    metadata:
      labels:
        app: crm
    spec:
      containers:
      - name: crm-app
        image: pwstaging/demo-crm:latest
        env:
        - name: LOG_LEVEL
          value: info
        - name: PERSISTENCE
          value: "true"
        - name: MONGODB_URI
          value: mongodb://root:XlYpHz4PMi@mongo-mongodb-headless:27017
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
















